//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcaddy.AudiPoiDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mcaddy.AudiPoiDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bitmaps/image_{0}.png,0,0,33,33,-24,-24.
        /// </summary>
        internal static string BitmapFormat {
            get {
                return ResourceManager.GetString("BitmapFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\PersonalPOI\Package\0\default\{1}.
        /// </summary>
        internal static string DataFilePath {
            get {
                return ResourceManager.GetString("DataFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #############################################################################   
        ///#  	
        ///# This is the description file for the Software Update of Audi components
        ///#
        ///#############################################################################
        ///
        ///[common]
        ///skipSaveTrainName = &quot;true&quot;
        ///vendor = &quot;AUDI&quot;
        ///region = &quot;Europe&quot;
        ///variant = &quot;FMU-*-*-EU-AU*&quot;
        ///variant2 = &quot;FMU-*-*-EU-VW*&quot;
        ///variant3 = &quot;FM2-*-*-EU-VW-*&quot;
        ///variant4 = &quot;FM2-*-*-EU-AU-*&quot;
        ///variant5 = &quot;FM2-*-*-EU-PO*&quot; 
        ///variant6 = &quot;FM2-*-*-EU-PO-*&quot;
        ///release = &quot;201 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metainfo2TxtTemplate {
            get {
                return ResourceManager.GetString("metainfo2TxtTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stacking_2 {
            get {
                object obj = ResourceManager.GetObject("stacking_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stacking_3 {
            get {
                object obj = ResourceManager.GetObject("stacking_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\PersonalPOI\InfoFile\0\default\Update.txt.
        /// </summary>
        internal static string UpdateTxtFilePath {
            get {
                return ResourceManager.GetString("UpdateTxtFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to device=PersonalPOI
        ///
        ///name.default=myAudi special destinations
        ///name.de_DE=myAudi Sonderziele
        ///name.en_GB=myAudi special destinations
        ///name.en_SA=myAudi points of interest
        ///name.es_ES=myAudi destinos especiales
        ///name.fr_FR=Destinations spéciales myAudi
        ///name.it_IT=Destinazioni speciali myAudi
        ///name.nl_NL=myAudi bijzondere reisdoelen
        ///name.pt_PT=myAudi destinos especiais
        ///name.ru_RU=myAudi oсобые цели
        ///name.pl_PL=myAudi cele specjalne
        ///name.cs_CZ=zvláštní cíle myAudi
        ///name.nb_NO=myAudi spesialmål
        ///name.sv_SE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateTxtTemplate {
            get {
                return ResourceManager.GetString("UpdateTxtTemplate", resourceCulture);
            }
        }
    }
}
