//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POILoaderBackend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POILoaderBackend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAhCAYAAABX5MJvAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAACxEAAAsRAX9kX5EAAADlSURBVFhHzY5BigQxDAPn/5/unYPZiCJWNDmYLhAYShH5PC/g5Z/4fJWG0CedBmMOA/RJp8GYwwB90mkw5jBAn3QaluGDiRRyoTCRQi4UJlLIhcJEinWR5sFPhBvGZAOWcMOYbMASbhiTDVjCjWX4gLlht6Mp5EKBuWG3oynkQoG5YbejKeRCgblht6Mp5EKBuWG3oynWRZoHPxFuGJMNWMINY7IBS7hhTDZgCTeW4YOJFHKhMJFCLhQmUsiFwkSKdZHmwT/0SafBmMMAfdJpMOYwQJ90Gow5DNAnnYbeDPKCTzzPH2cvN4DGtHK8AAAAAElFTkSuQmCC.
        /// </summary>
        internal static string EnglishHeritageIconBase64 {
            get {
                return ResourceManager.GetString("EnglishHeritageIconBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAhCAIAAADYhlU4AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAHYcAAB2HAY/l8WUAAAdFSURBVEhL3ZZ7TFv3Fce95sEzzaptUlVp0lYxDPhtTCAGGzs8zNM29n2Y4ADlmZAGYgwYiHkb0uDyCJQSIEDAGAzGYPNIMOFVIJAEWkIpzapWbbV/tknTpP2xf6edm+sQ2KD/9Z9KX135nnvu+XB+53GhBL+D/tz6hTEu/Br1O6WivoWT8juFgQXsXG/El4KC/kQI4Xghr5wR6q+UPhSQAhRwWkkGoZ1RvE+Rv5aM4aYg7QQDwjHcsOfdvKVW/kq7cL1TtNoRyfLAIGJKEP7SJtsZUuxakO9nVWkhhJHpjuyOZf7ozPnBee1vazdGDVcBAwBT5bV/7+r/uVX5ry+q//PdbWPOdRLjYtDd8Hkjb6Im1F4nmG4In7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HistoricHousesIconBase64 {
            get {
                return ResourceManager.GetString("HistoricHousesIconBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAhCAYAAABX5MJvAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAccSURBVFhHlVdZbJRVFP5bYvRBCK3bmyYkSKLGBzBIoggxLqDGQIzRmPhkjPpgosKDYKWdthRoSzdaIBZoUIRC6EJLF7rOdEpLl+lGaW1ZW7ayGA3QveXzO3f++/fOdCAyyeldz3e+e+455/61rFQvlKTUzbSh+tsbYCVWw0qScb2/TfIgbDvXkmphJXu4V/axlbXkk+yzTeNeERNLxqZN9UdPmJsDxIsF2R58Wngaq462wkqowMd5bfiksB2Pp9dh0d5TWHusDUsPNJNAPdYUdWFNYQvmpJGIxtc2Qo0DJh5EItGDde5eyG9k+h7CNheovvw+yD2FIz1/qb7vxhAWZLlVX37zMm3vCIbYCMbXth9IQvpaEt34vq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HistoricScotlandIconBase64 {
            get {
                return ResourceManager.GetString("HistoricScotlandIconBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAhCAYAAABX5MJvAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAHYYAAB2GAV2iE4EAAAYFSURBVFhHzVdpTFRXFPZXfzSmarSGaN1QXHGhtjWp2iX1tzFNTdOktrZJ26RN2qZq06ZqFJV9GBgGF9CairbuQlVmY5gFUIFhZlBkmEGBAIOgoFZEIgzz9dz77jDbg1DbpH5wct87dznfPefcc9+My7Um4P+W55eE2rICuZZAKwl7VsuMlZPAPDVfg3RMZMYFJIoEX4BalSUemab5UJoWIqN0HulWINu0aLg/UhhBNY1h/TmWZVCaF3Ei2dSqLctHJSLrCZVlKX4tWwNH6zFcdH4DZ+txJGljUFz3HZGazw3xHYrx7DmH5qTqZyKzdC4Ol78Nq3sv9mkn4NKNb5FhmsWJca+G2AmIrCeyTItRaP8Mobj/uIW352 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NationalTrustIconBase64 {
            get {
                return ResourceManager.GetString("NationalTrustIconBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAhCAYAAABX5MJvAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFxIAABcSAWef0lIAAAAhdEVYdENyZWF0aW9uIFRpbWUAMjAxNjoxMDoxOCAxNDo1MToyMr7DqZEAAAb0SURBVFhHxVh5cE1XHP7eyyZEIhKpBBFbhNTWIlPEvlQmllFjmNYgVUupnaGtjlTbKVV/MKNMUXuHiNgZYhmUSCoVGiRUX8gii8pmefFebr/fXZ4gUgz6zdx3z73nd875zm8995n2puYokSt+A6q7As5m/B8wKYTNZofLvP18VAAXJ63nDYJbV+Ds7ATlhwFwdXUGHtr1rjcHaqKc21eb2u/cvUB5OU3z5jRSgYRAJzJ9J+BKEk5P+IhCURsJyiVtgciICc3a2JfBEyQEJtwutcJ39h6gVjXtlYiU0UyKGZFhTTCkTQMEeddAcZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RSBPIconBase64 {
            get {
                return ResourceManager.GetString("RSBPIconBase64", resourceCulture);
            }
        }
    }
}
